"""
A QA Bot that leverages RAG and LangChain to answer questions about uploaded documents.

This is run through the IBM Skills Network Labs virtual environment.

Final task of Project: Generative AI Applications with RAG and LangChain
(https://www.coursera.org/learn/project-generative-ai-applications-with-rag-and-langchain/home/welcome)
"""

import warnings

from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain.chains import RetrievalQA
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyPDFLoader
from langchain_community.vectorstores import Chroma

import gradio as gr

def warn(*args, **kwargs):
    """ Function to ignore warnings generated by code """

warnings.warn = warn
warnings.filterwarnings('ignore')


def get_llm():
    """ Load Watson LLM """
    model_id = 'ibm/granite-3-2-8b-instruct'
    parameters = {
        GenParams.MAX_NEW_TOKENS: 256,  # Max number of tokens in generated output
        GenParams.TEMPERATURE: 0.5,  # Randomness or creativity of model's responses
    }
    project_id = "skills-network"
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id=project_id,
        params=parameters,
    )
    return watsonx_llm


def document_loader(file):
    """ Load document """
    loader = PyPDFLoader(file.name)
    return loader.load()


def text_splitter(data):
    """ Split document into chunks """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=20,
        length_function=len,
    )
    return splitter.split_documents(data)


def watsonx_embedding():
    """ Create object to generate embeddings """
    embed_params = {
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 3,
        EmbedTextParamsMetaNames.RETURN_OPTIONS: {"input_text": True},
    }
    return WatsonxEmbeddings(
        model_id="ibm/slate-125m-english-rtrvr",
        url="https://us-south.ml.cloud.ibm.com",
        project_id="skills-network",
        params=embed_params,
    )


def vector_database(chunks):
    """ Create vector database """
    embedding_model = watsonx_embedding()
    return Chroma.from_documents(chunks, embedding_model)


def retriever(file):
    """ Create retriever to fetch document segments based on queries """
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    return vectordb.as_retriever()


def retriever_qa(file, query):
    """ Create question-answering chain """
    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(llm=llm,
                                    chain_type="stuff",
                                    retriever=retriever_obj,
                                    return_source_documents=False)
    response = qa.invoke(query)
    return response['result']


# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    allow_flagging="never",
    inputs=[
        # Drag and drop file upload
        gr.File(label="Upload PDF", file_count="single", file_types=['.pdf'], type="filepath"),
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output"),
    title="QA bot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using "
                "the provided document."
)


# Launch the app
rag_application.launch(server_name="127.0.0.1", server_port=7860)

